sheetType:
    source: source
    master: master
    compare: compare
    sap: sap
statusLabels:
    reference: reference
    new: new
    updated: updated
columnLabels:
    date: date
    status: status
    search: searchIndex
paths:
  log: ./runs
  data: ${hydra:runtime.cwd}/data/
  settingsXML: ${hydra:runtime.cwd}/settingsXML/