defaults:
    - program_setting_schema

sheetType:
    source: source
    master: master
    compare: compare
    sap: sap
statusLabels:
    reference: reference
    new: new
    updated: updated
    current: current
    change: change
columnLabels:
    date: date
    status: status
    search: searchIndex
    partNumber: partNumber
paths:
  log: ./runs
  data: ${hydra:runtime.cwd}/data/
  settingsXML: ${hydra:runtime.cwd}/settingsXML/